---
- name: Install PostgreSQL 13.23 specific package
  ansible.builtin.dnf:
    name: "postgresql13-server-13.23"
    state: present
  when: ansible_os_family == "RedHat"
  tags: [postgresql, install]

- name: Install chrony client
  ansible.builtin.dnf:
    name: chrony
    state: present
  when: ansible_os_family == "RedHat"
  tags: [chrony_client, install]

- name: Deploy chrony client configuration
  ansible.builtin.copy:
    src: chrony-client.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify: Restart chrony client
  tags: [chrony_client, config]

- name: Ensure chrony client is enabled and running
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
  tags: [chrony_client, service]

- name: Deploy ACL
  ansible.builtin.copy:
    src: pg_hba.conf
    dest: "{{ postgresql_hba_dest }}"
    owner: postgres
    group: postgres
    mode: "0600"
  notify: Reload postgresql
  tags: [postgresql, config]

- name: Ensure PostgreSQL service is enabled and running
  ansible.builtin.service:
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: true
  tags: [postgresql, service]