---
all:
  children:
    ntp:
      hosts:
        ntp:
          ansible_host: 192.168.1.10
    app:
      hosts:
        app:
          ansible_host: 192.168.1.20
    db:
      hosts:
        db:
          ansible_host: 192.168.1.30