---
- name: Reload postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service_name }}"
    state: reloaded

- name: Restart chrony client
  ansible.builtin.service:
    name: chronyd
    state: restarted